
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author joaom
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listEventos = new javax.swing.JList<>();
        jPanel4 = new javax.swing.JPanel();
        listAtletas = new javax.swing.JScrollPane();
        athleteList = new javax.swing.JList<>();
        lblEventos = new javax.swing.JLabel();
        lblAtletas = new javax.swing.JLabel();
        btnCriarEvento = new javax.swing.JButton();
        btnEditarEvento = new javax.swing.JButton();
        btnEliminarEvento = new javax.swing.JButton();
        btnMostrarMaisMedalhasPais = new javax.swing.JButton();
        btnCriarAtleta = new javax.swing.JButton();
        btnEditarAtleta = new javax.swing.JButton();
        btnMostrarHistoricoAtleta = new javax.swing.JButton();
        btnMostraInscricoes = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnImportarEventos = new javax.swing.JButton();
        btnImportarAtletas = new javax.swing.JButton();
        btnMostrarAtleta = new javax.swing.JButton();
        btnMostrarEvento = new javax.swing.JButton();

        jButton3.setText("Eliminar Evento");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Home");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        listEventos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Evento X - 2023-06-23/2023-06-26" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listEventos);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );

        athleteList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Atleta X" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listAtletas.setViewportView(athleteList);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listAtletas, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listAtletas, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
        );

        lblEventos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblEventos.setText("Gestão Eventos");

        lblAtletas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAtletas.setText("Gestão Atletas");

        btnCriarEvento.setBackground(new java.awt.Color(153, 153, 153));
        btnCriarEvento.setForeground(new java.awt.Color(255, 255, 255));
        btnCriarEvento.setText("Criar Evento");
        btnCriarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarEventoActionPerformed(evt);
            }
        });

        btnEditarEvento.setBackground(new java.awt.Color(153, 153, 153));
        btnEditarEvento.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarEvento.setText("Editar Evento");
        btnEditarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarEventoActionPerformed(evt);
            }
        });

        btnEliminarEvento.setBackground(new java.awt.Color(153, 153, 153));
        btnEliminarEvento.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarEvento.setText("Eiminar Evento");
        btnEliminarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEventoActionPerformed(evt);
            }
        });

        btnMostrarMaisMedalhasPais.setBackground(new java.awt.Color(153, 153, 153));
        btnMostrarMaisMedalhasPais.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrarMaisMedalhasPais.setText("Ver Países mais Medalhados");

        btnCriarAtleta.setBackground(new java.awt.Color(153, 153, 153));
        btnCriarAtleta.setForeground(new java.awt.Color(255, 255, 255));
        btnCriarAtleta.setText("Criar Atleta");
        btnCriarAtleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarAtletaActionPerformed(evt);
            }
        });

        btnEditarAtleta.setBackground(new java.awt.Color(153, 153, 153));
        btnEditarAtleta.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarAtleta.setText("Editar Atleta");
        btnEditarAtleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarAtletaActionPerformed(evt);
            }
        });

        btnMostrarHistoricoAtleta.setBackground(new java.awt.Color(153, 153, 153));
        btnMostrarHistoricoAtleta.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrarHistoricoAtleta.setText("Ver Histórico");

        btnMostraInscricoes.setBackground(new java.awt.Color(153, 153, 153));
        btnMostraInscricoes.setForeground(new java.awt.Color(255, 255, 255));
        btnMostraInscricoes.setText("Ver Inscrições");

        btnSair.setBackground(new java.awt.Color(255, 0, 0));
        btnSair.setForeground(new java.awt.Color(255, 255, 255));
        btnSair.setText("Sair");

        btnImportarEventos.setBackground(new java.awt.Color(153, 153, 153));
        btnImportarEventos.setForeground(new java.awt.Color(255, 255, 255));
        btnImportarEventos.setText("Importar Evento");
        btnImportarEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportarEventosActionPerformed(evt);
            }
        });

        btnImportarAtletas.setBackground(new java.awt.Color(153, 153, 153));
        btnImportarAtletas.setForeground(new java.awt.Color(255, 255, 255));
        btnImportarAtletas.setText("Importar Atletas");

        btnMostrarAtleta.setBackground(new java.awt.Color(153, 153, 153));
        btnMostrarAtleta.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrarAtleta.setLabel("Ver Atleta");
        btnMostrarAtleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarAtletaActionPerformed(evt);
            }
        });

        btnMostrarEvento.setBackground(new java.awt.Color(153, 153, 153));
        btnMostrarEvento.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrarEvento.setLabel("Ver Evento");
        btnMostrarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarEventoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAtletas, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnImportarEventos)
                            .addGap(18, 18, 18)
                            .addComponent(btnImportarAtletas))
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(lblEventos, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMostrarMaisMedalhasPais, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnEditarEvento, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                        .addComponent(btnCriarEvento, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                        .addComponent(btnEliminarEvento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCriarAtleta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditarAtleta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMostrarHistoricoAtleta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMostraInscricoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMostrarAtleta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMostrarEvento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnSair))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(lblEventos))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMostrarMaisMedalhasPais)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnMostrarEvento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCriarEvento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditarEvento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminarEvento)))
                .addGap(33, 33, 33)
                .addComponent(lblAtletas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnMostrarAtleta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCriarAtleta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditarAtleta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMostrarHistoricoAtleta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMostraInscricoes)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImportarAtletas)
                    .addComponent(btnImportarEventos)
                    .addComponent(btnSair))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarEventoActionPerformed
          
        JFrame home = new PaginaEventoEditar();
        home.show();
        dispose();
    }//GEN-LAST:event_btnEditarEventoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnEliminarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEventoActionPerformed
               
        UIManager.put("OptionPane.noButtonText", "Cancelar");
        UIManager.put("OptionPane.yesButtonText", "Sim");
        int result = JOptionPane.showConfirmDialog(this, "Deseja apagar o evento 'Evento X'", "Confirme Alterações",  JOptionPane.YES_NO_OPTION);
    }//GEN-LAST:event_btnEliminarEventoActionPerformed

    private void btnMostrarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarEventoActionPerformed
                          
        JFrame home = new PaginaEvento();
        home.show();
        dispose();
    }//GEN-LAST:event_btnMostrarEventoActionPerformed

    private void btnCriarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarEventoActionPerformed
        
        JFrame home = new PaginaEventoCriar();
        home.show();
        dispose();
    }//GEN-LAST:event_btnCriarEventoActionPerformed

    private void btnImportarEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportarEventosActionPerformed
        
        JFrame home = new PaginaEventoImportar();
        home.show();
        dispose();
    }//GEN-LAST:event_btnImportarEventosActionPerformed

    private void btnMostrarAtletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarAtletaActionPerformed

        JFrame home = new PaginaAtleta();
        home.show();
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnMostrarAtletaActionPerformed

    private void btnCriarAtletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarAtletaActionPerformed
        
        JFrame home = new PaginaAtletaCriar();
        home.show();
        dispose();
    }//GEN-LAST:event_btnCriarAtletaActionPerformed

    private void btnEditarAtletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarAtletaActionPerformed
        
        JFrame home = new PaginaAtletaEditar();
        home.show();
        dispose();
    }//GEN-LAST:event_btnEditarAtletaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> athleteList;
    private javax.swing.JButton btnCriarAtleta;
    private javax.swing.JButton btnCriarEvento;
    private javax.swing.JButton btnEditarAtleta;
    private javax.swing.JButton btnEditarEvento;
    private javax.swing.JButton btnEliminarEvento;
    private javax.swing.JButton btnImportarAtletas;
    private javax.swing.JButton btnImportarEventos;
    private javax.swing.JButton btnMostraInscricoes;
    private javax.swing.JButton btnMostrarAtleta;
    private javax.swing.JButton btnMostrarEvento;
    private javax.swing.JButton btnMostrarHistoricoAtleta;
    private javax.swing.JButton btnMostrarMaisMedalhasPais;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAtletas;
    private javax.swing.JLabel lblEventos;
    private javax.swing.JScrollPane listAtletas;
    private javax.swing.JList<String> listEventos;
    // End of variables declaration//GEN-END:variables
}
