
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author joaom
 */
public class PaginaEvento extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public PaginaEvento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        list1 = new java.awt.List();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        competionList = new javax.swing.JList<>();
        deleteCompetitionBtn6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        createCompetitionBtn = new javax.swing.JButton();
        editCompetitionBtn = new javax.swing.JButton();
        deleteCompetitionBtn = new javax.swing.JButton();
        showCompetitionBtn = new javax.swing.JButton();
        showEnrollmentsBtn = new javax.swing.JButton();
        importEnrollmentBtn = new javax.swing.JButton();
        startEventBtn = new javax.swing.JButton();
        showCalendarBtn = new javax.swing.JButton();
        showMostMedalsBtn = new javax.swing.JButton();
        importCompetitionBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Evento X");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0));

        jButton1.setText("<-");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        competionList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Prova X - 2023-06-23/2023-06-26 - A decorrer", "Prova Y - 2023-06-23/2023-04-24 - Finalizada" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(competionList);

        deleteCompetitionBtn6.setBackground(new java.awt.Color(153, 153, 153));
        deleteCompetitionBtn6.setForeground(new java.awt.Color(255, 255, 255));
        deleteCompetitionBtn6.setText("Ver Países mais Medalhados");
        deleteCompetitionBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCompetitionBtn6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(deleteCompetitionBtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deleteCompetitionBtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Provas");

        createCompetitionBtn.setBackground(new java.awt.Color(153, 153, 153));
        createCompetitionBtn.setForeground(new java.awt.Color(255, 255, 255));
        createCompetitionBtn.setText("Criar Prova");
        createCompetitionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createCompetitionBtnActionPerformed(evt);
            }
        });

        editCompetitionBtn.setBackground(new java.awt.Color(153, 153, 153));
        editCompetitionBtn.setForeground(new java.awt.Color(255, 255, 255));
        editCompetitionBtn.setText("Editar Prova");
        editCompetitionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCompetitionBtnActionPerformed(evt);
            }
        });

        deleteCompetitionBtn.setBackground(new java.awt.Color(153, 153, 153));
        deleteCompetitionBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteCompetitionBtn.setText("Eliminar Prova");
        deleteCompetitionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCompetitionBtnActionPerformed(evt);
            }
        });

        showCompetitionBtn.setBackground(new java.awt.Color(153, 153, 153));
        showCompetitionBtn.setForeground(new java.awt.Color(255, 255, 255));
        showCompetitionBtn.setText("Ver Prova");
        showCompetitionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showCompetitionBtnActionPerformed(evt);
            }
        });

        showEnrollmentsBtn.setBackground(new java.awt.Color(153, 153, 153));
        showEnrollmentsBtn.setForeground(new java.awt.Color(255, 255, 255));
        showEnrollmentsBtn.setText("Ver Inscritos");
        showEnrollmentsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showEnrollmentsBtnActionPerformed(evt);
            }
        });

        importEnrollmentBtn.setBackground(new java.awt.Color(153, 153, 153));
        importEnrollmentBtn.setForeground(new java.awt.Color(255, 255, 255));
        importEnrollmentBtn.setText("Importar Inscrição");
        importEnrollmentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importEnrollmentBtnActionPerformed(evt);
            }
        });

        startEventBtn.setBackground(new java.awt.Color(153, 153, 153));
        startEventBtn.setForeground(new java.awt.Color(255, 255, 255));
        startEventBtn.setText("Lançar Evento");
        startEventBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startEventBtnActionPerformed(evt);
            }
        });

        showCalendarBtn.setBackground(new java.awt.Color(153, 153, 153));
        showCalendarBtn.setForeground(new java.awt.Color(255, 255, 255));
        showCalendarBtn.setText("Ver Calendário");
        showCalendarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showCalendarBtnActionPerformed(evt);
            }
        });

        showMostMedalsBtn.setBackground(new java.awt.Color(153, 153, 153));
        showMostMedalsBtn.setForeground(new java.awt.Color(255, 255, 255));
        showMostMedalsBtn.setText("Ver Países mais Medalhados");
        showMostMedalsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showMostMedalsBtnActionPerformed(evt);
            }
        });

        importCompetitionBtn.setBackground(new java.awt.Color(153, 153, 153));
        importCompetitionBtn.setForeground(new java.awt.Color(255, 255, 255));
        importCompetitionBtn.setText("Importar Prova");
        importCompetitionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importCompetitionBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(importEnrollmentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(showMostMedalsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(showEnrollmentsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(importCompetitionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(showCompetitionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editCompetitionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(createCompetitionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteCompetitionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(showCalendarBtn)
                            .addComponent(startEventBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(showCompetitionBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(createCompetitionBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editCompetitionBtn)
                        .addGap(12, 12, 12)
                        .addComponent(deleteCompetitionBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(importCompetitionBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(showEnrollmentsBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(showCalendarBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(startEventBtn))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showMostMedalsBtn)
                    .addComponent(importEnrollmentBtn))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showCompetitionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showCompetitionBtnActionPerformed
        
        JFrame home = new PaginaProva();
        home.show();
        dispose();  
    }//GEN-LAST:event_showCompetitionBtnActionPerformed

    private void deleteCompetitionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCompetitionBtnActionPerformed
        UIManager.put("OptionPane.noButtonText", "Cancelar");
        UIManager.put("OptionPane.yesButtonText", "Sim");
        int result = JOptionPane.showConfirmDialog(this, "Esta ação vai pagar a prova 'Prova X'. \n Deseja proceder?", "Eliminar Evento",  JOptionPane.YES_NO_OPTION);        // TODO add your handling code here:
    }//GEN-LAST:event_deleteCompetitionBtnActionPerformed

    private void editCompetitionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCompetitionBtnActionPerformed
        
        JFrame home = new PaginaEditarProva();
        home.show();
        dispose();   
    }//GEN-LAST:event_editCompetitionBtnActionPerformed

    private void showEnrollmentsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showEnrollmentsBtnActionPerformed
        
        JFrame home = new PaginaEventoIncritos();
        home.show();
        dispose();      
    }//GEN-LAST:event_showEnrollmentsBtnActionPerformed

    private void importEnrollmentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importEnrollmentBtnActionPerformed
        
        JFrame home = new PaginaImportarInscricao();
        home.show();
        dispose();      
    }//GEN-LAST:event_importEnrollmentBtnActionPerformed

    private void startEventBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startEventBtnActionPerformed
        UIManager.put("OptionPane.noButtonText", "Cancelar");
        UIManager.put("OptionPane.yesButtonText", "Sim");
        int result = JOptionPane.showConfirmDialog(this, "Esta ação vai lançar o Evento X, abrindo as suas inscrições. \n Deseja proceder?", "Lançar Evento",  JOptionPane.YES_NO_OPTION);        
    }//GEN-LAST:event_startEventBtnActionPerformed

    private void showCalendarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showCalendarBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showCalendarBtnActionPerformed

    private void deleteCompetitionBtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCompetitionBtn6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteCompetitionBtn6ActionPerformed

    private void showMostMedalsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showMostMedalsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showMostMedalsBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        JFrame home = new Home();
        home.show();
        dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void importCompetitionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importCompetitionBtnActionPerformed
        
        JFrame home = new PaginaImportarProva();
        home.show();
        dispose();         // T
    }//GEN-LAST:event_importCompetitionBtnActionPerformed

    private void createCompetitionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createCompetitionBtnActionPerformed
        
        JFrame home = new PaginaCriarProva();
        home.show();
        dispose();   
    }//GEN-LAST:event_createCompetitionBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> competionList;
    private javax.swing.JButton createCompetitionBtn;
    private javax.swing.JButton deleteCompetitionBtn;
    private javax.swing.JButton deleteCompetitionBtn6;
    private javax.swing.JButton editCompetitionBtn;
    private javax.swing.JButton importCompetitionBtn;
    private javax.swing.JButton importEnrollmentBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.List list1;
    private javax.swing.JButton showCalendarBtn;
    private javax.swing.JButton showCompetitionBtn;
    private javax.swing.JButton showEnrollmentsBtn;
    private javax.swing.JButton showMostMedalsBtn;
    private javax.swing.JButton startEventBtn;
    // End of variables declaration//GEN-END:variables
}
